### ISSUE TITLE
Can't get port on OS X (no netstat -p)

### ISSUE THREAD

**Issue by adamv** [stephenmcd/gunicorn-console#3]
netstat (BSD) on OS X doesn't suport -p to output PIDs.

I'm working on some alternate code that will do it with lsof, though lsof is an external command (`brew lsof`). If someone else knows a smarter, built-in way to emulate netstat -p, let me know.

**Comment by adamv** [comment]
Added some code that "seems to work" here:
http://github.com/adamv/gunicorn-console/commit/1f35f0b7a0062fcf2542f29f34515c79f5a84954

I'm open to style / strategy suggestions.

**Comment by stephenmcd** [comment]
Will do for now, I've merged these changes. Thanks Adam.
