### ISSUE TITLE
gunicorn not getting detected

### ISSUE THREAD

**Issue by ashokrkm** [stephenmcd/gunicorn-console#4]
how should the gunicorn process be named in config file? is there a specific pattern to use?
these are the gunicorn processes running, and are not getting detected

http://pastie.org/1283297

**Comment by stephenmcd** [comment]
Processes are named with "gunicorn: master" and "gunicorn: worker" by default if you have the setproctitle package installed so you don't need to name them specifically. 

From the output you showed I'm guessing you don't have setproctitle installed.

**Comment by ashokrkm** [comment]
thanks a lot! i had to install setproctitle and add proc_name=xxx in my gunicorn config file and everything works!

thanks for this nifty tool, very useful

**Comment by stephenmcd** [comment]
Thanks, glad you like it!
