### ISSUE TITLE
detect gunicorn_django

### ISSUE THREAD

**Issue by yashh** [stephenmcd/gunicorn-console#6]
Hey I am using gunicorn_django -c gunicorn_conf.py. here's how my ps -aux looks

```
/usr/bin/python /usr/local/bin/gunicorn_django -c /mnt/myproject/gunicorn.conf.py
```

I do have proc_name in the config set to "gunicorn". Does console detect gunicorn_django ?

**Comment by paparent** [comment]
Maybe you don't have setproctitle installed ?

```
easy_install setproctitle
```

**Comment by stephenmcd** [comment]
I've added an explicit check for setproctitle which tells the user to install it if required.

**Comment by yashh** [comment]
Damn I thought i had setproctitle installed. But you are right. easy_install seems to error out but pip succeded. Got it working thanks.
