### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by mw44118** [stephenmcd/gunicorn-console#7]
I already had a gunicorn running.  Then I installed gunicorn-console and fired it up.  It doesn't think there are any gunicorns running!

What did I do wrong?

Matt

PS: neat app, BTW!

**Comment by stephenmcd** [comment]
Did you install setproctitle?

**Comment by mw44118** [comment]
yes

**Comment by stephenmcd** [comment]
If you run the ps command and paste the output it might show something useful

**Comment by mw44118** [comment]
Well, I killed my app and restarted it, and now it works.  Before, I just fired up gunicorn-console after installing it, but my gunicorn server process had been running for days.

Nice!
