### ISSUE TITLE
minor rpmlint warnings

### ISSUE THREAD

**Issue by Ammler** [stephenmcd/gunicorn-console#8]
python-gunicorn-console.noarch: W: non-executable-script /usr/lib/python2.7/site-packages/gunicorn_console.py 0644L /usr/bin/env
This text file contains a shebang or is located in a path dedicated for
executables, but lacks the executable bits and cannot thus be executed.  If
the file is meant to be an executable script, add the executable bits,
otherwise remove the shebang or move the file elsewhere.

python-gunicorn-console.noarch: W: no-manual-page-for-binary gunicorn-console
Each executable in standard binary directories should have a man page.

**Comment by stephenmcd** [comment]
This project doesn't distribute an RPM.

**Comment by Ammler** [comment]
it's not about distributed rpms, this are issues, if you build a rpm. I just forwarded this to you so you are aware of it. Well you closed the issue without comment. So never mind. ;-)

**Comment by stephenmcd** [comment]
You haven't mentioned how you obtained the source code, but on github, bitbucket and pypi the execute bit is set on gunicorn_console.py

I've yet to ever come across a Python package hosted on any of those services that contains man pages.

**Comment by Ammler** [comment]
the rpm project is for suse: 
https://build.opensuse.org/package/show?package=python-gunicorn-console&project=devel%3Alanguages%3Apython
sources are from:
http://pypi.python.org/packages/source/g/%{mod}/%{mod}-%{version}.tar.gz
(as you can see here:
https://build.opensuse.org/package/view_file?file=python-gunicorn-console.spec&package=python-gunicorn-console&project=devel%3Alanguages%3Apython)
you find also build logs there, maybe it is an issue from spec or the setup.py

**Comment by stephenmcd** [comment]
I don't know anything about RPM packaging, but like I said it really falls outside the scope of the Python package itself.

If there's anything that needs to change in the Python package to make things easier please go right ahead and submit a pull request.
